name: Deploy Nightly
on:
  schedule:
    - cron: '20 14 * * *' # run at 2 AM UTC
  workflow_dispatch:


jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11.0, macos-10.15, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/checkout@master
        with:
          repository: masinter/medley
          path: ./medley
          
      - uses: actions/checkout@master
        with:
         repository: masinter/maiko
         path: ./maiko
          
      - name: Install X11 dependencies on MacOS
        if: ${{ runner.os == 'macOS'}}
        run: brew install xterm
      - name: Install X11 dependencies on Linux
        if: ${{ runner.os == 'Linux'}}
        run:  |
          echo "A initial message"
          sudo apt-get update
          sudo apt-get install -y xserver-xorg-core openbox xauth xvfb tightvncserver
          echo "A initial message"
          export DISPLAY=':99.0'
          echo "A initial message"
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - name: Install X11 onLinux
        if: ${{ runner.os == 'Linux'}}
        run:  |
          Xvnc -geometry 1270x720 :0 & DISPLAY=:0 /app/ldex -g 1280x720 full.sysout
          #Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &  
          echo "A initial message"
          export DISPLAY=':99.0'
          echo "A initial message"    
      - name: Show Working directory
        if: ${{ runner.os == 'macOS'}}
        run: ls /Library/LaunchAgents/
      - name: Show Working directory
        run: export DISPLAY=':99.0'
      - name: set env
        if: ${{ runner.os == 'macOS'}}
        run: xterm -geometry 93x31+100+350
      - name: Build Maiko
        working-directory: maiko/bin
        run: ./makeright x
      - name: Build Maiko
        working-directory: maiko/bin
        run: ./makeright init
      - name: run medley
        working-directory: medley
        run: ./run-medley 
      - name: Build medley
        working-directory: medley
        run: ./scripts/loadup-all.sh   
        

        
        
        
        
  
      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
