name: Deploy Nightly
on:
  schedule:
    - cron: '20 14 * * *' # run at 2 AM UTC
  workflow_dispatch:


jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    
    steps:
    
      - uses: actions/checkout@master
        with:
          repository: masinter/medley
          path: ./medly
          
      - uses: actions/checkout@master
        with:
         repository: masinter/maiko
         path: ./maiko
          
      - name: Install X11 dependencies on MacOS
        if: ${{ runner.os == 'macOS'}}
        run: brew install --cask xquartz
      - name: Build Maiko
        #working-directory: bin
        run: ./maiko/bin/makeright x
      - name: Build Maiko
        #working-directory: bin
        run: ./maiko/bin/makeright init
      - name: Build medley
        #working-directory: medley
        run: ./medley/scripts/loadup-all.sh   
        

        
        
        
        
  
      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
