name: Deploy Nightly
on:
  schedule:
    - cron: '20 14 * * *' # run at 2 AM UTC
  workflow_dispatch:


jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Install X11 dependencies on MacOS
        if: ${{ runner.os == 'macOS'}}
        run: brew install --cask xquartz
      - name: Build
        working-directory: bin
        run: ./makeright x
  
      - name: Deploy Windows release
        if: matrix.os == 'windows-latest'
        uses: WebFreak001/deploy-nightly@v1.1.0
